db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c5
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e5
db $c4, $c4, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $c4, $c5
db $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $f1, $e5
db $dd, $de, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $dc, $dd
db $dd, $de, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40, $41, $42, $43
db $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $60, $61, $62, $63
db $64, $65, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $dc, $dd
db $fd, $fe, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $80, $81, $82, $83
db $84, $85, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $fc, $fd
db $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $a0, $a1, $a2, $a3
db $a4, $a5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c2, $c3
db $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $6e, $6f, $70, $ff, $e2, $e3
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $3b, $3c, $3d, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $5b, $5c, $5d, $ff, $ff, $ff
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $c4, $c5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $ff, $ff
db $ff, $ff, $dc, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $c5, $c5
db $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fe, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c5, $c5
db $dd, $de, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $ff, $ff
db $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $c4, $c5
db $dd, $de, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $e4, $e5, $e4, $e5, $e4, $e5, $e4, $e5, $e4, $e5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $c5, $e4, $e4, $e5, $e4, $e5, $e5, $e4, $e5, $e5
db $dd, $de, $ff, $ff, $ff, $ff, $40, $41, $42, $43, $44, $45, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $e4, $e5, $c5, $e4, $e5, $c4, $c4, $c5, $e5, $c4, $c5, $e5
db $dd, $de, $ff, $ff, $c0, $c1, $60, $61, $62, $63, $64, $65, $c0, $c1, $ff, $c0
db $c1, $ff, $dc, $dd, $c4, $c5, $c5, $c4, $c5, $c4, $e4, $e5, $e5, $e4, $e5, $c5
db $dd, $de, $ff, $ff, $e0, $e1, $80, $81, $82, $83, $84, $85, $e0, $e1, $ff, $e0
db $e1, $ff, $dc, $dd, $c4, $c5, $c5, $e4, $e5, $c4, $e4, $e5, $c4, $e4, $e5, $c5

db $dd, $de, $ff, $ff, $ff, $ff, $a0, $a1, $a2, $a3, $a4, $a5, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $c5, $e4, $e5, $c4, $c5, $e4, $e4, $e4, $c4, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $c4, $c5, $c5, $c4, $c4, $c5, $c4, $c5, $e4, $e5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $e4, $e5, $e5, $c4, $e4, $e5, $e4, $e5, $c4, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $c4, $c5, $c4, $c5, $e5, $c4, $c4, $c4, $e4, $e5, $c4, $c5
db $dd, $de, $ff, $ff, $bc, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $ef, $c5, $c4, $c5, $e4, $e5, $e5, $c4, $c4, $e4, $e4, $e5, $e4, $e5
db $dd, $de, $ff, $ff, $dc, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $e4, $e5, $c4, $c5, $c4, $c5, $c4, $e4, $c4, $e4, $e4, $e5, $e5, $c5
db $dd, $de, $ff, $ff, $dc, $dd, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c5, $c4, $e4, $c4, $c5, $e4, $e5, $e5, $e5
db $dd, $de, $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e5, $e4, $e5, $e4, $e5, $e4, $e5, $e5, $e5

db $dd, $de, $ff, $ff, $dc, $dd, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $dd, $de, $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $c4, $c5, $e4, $c4, $c5, $e4, $e4, $e4, $e5
db $dd, $de, $ff, $ff, $dc, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c5, $c4, $c4, $c5, $c5
db $dd, $de, $ff, $ff, $fc, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $f1, $c4, $c4, $c5, $e4, $c4, $c5, $e4, $c4, $c5, $c5, $c4, $c5, $c5
db $dd, $de, $ff, $ff, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c3, $dc, $e4, $c4, $c4, $c5, $e4, $e5, $c4, $c4, $c5, $c5, $c4, $c5, $c5
db $dd, $de, $ff, $ff, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e3, $dc, $e4, $e4, $c4, $c5, $c4, $c5, $e4, $c4, $c5, $e5, $c4, $c5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $c4, $c4, $c5, $c4, $c5, $c4, $c5, $c5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $c4, $c5, $e5, $c4, $c5, $e4, $e5, $c5, $c5

db $dd, $de, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $c4, $c5, $c5, $e4, $e5, $c4, $c5, $c5, $c5
db $dd, $de, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $c4, $c5, $e5, $c4, $c5, $e4, $e5, $c5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $e4, $e5, $c4, $c5, $c5, $c4, $c5, $e5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $6e, $6f, $70, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c5, $c4, $c5, $e4, $e5, $c5, $e4, $e5, $c5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $3b, $3c, $3d, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c4, $c4, $e4, $c4, $c5, $e5, $e5, $c5, $e4, $e5, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $5b, $5c, $5d, $ff, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $e4, $c4, $c4, $e4, $e5, $e4, $e4, $e5, $e4, $e5, $c5
db $c4, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $be, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $c5, $e4, $e4, $e4, $e4, $e5, $c5, $c5, $c5, $c5, $c5
db $e4, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $ff, $ff
db $ff, $ff, $dc, $e4, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3
db $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff, $ff, $ff, $ff, $40, $41, $42, $43
db $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff
db $bd, $be, $ff, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $60, $61, $62, $63
db $64, $65, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $ff, $ff, $ff, $bc, $bd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $80, $81, $82, $83
db $84, $85, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $ff, $ff, $ff, $dc, $dd

db $c4, $f0, $bd, $be, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $a0, $a1, $a2, $a3
db $a4, $a5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bc, $bd, $ef, $c5
db $c4, $c5, $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $71, $72, $73, $ff, $ff, $ff, $dc, $dd, $e4, $e5
db $c4, $c5, $c4, $f0, $bd, $be, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $3b, $3c, $3d, $ff, $bc, $bd, $ef, $c4, $e4, $e5
db $c4, $c5, $e4, $e5, $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $5b, $5c, $5d, $ff, $dc, $dd, $e4, $e4, $e4, $e5
db $c4, $c5, $e4, $e5, $c5, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $ef, $c4, $c4, $c4, $c4, $c5
db $c4, $c5, $e4, $e5, $e5, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $e4, $e4, $e4, $e4, $e4, $e5
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c5, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e5, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $96, $97, $98, $99, $9a, $9b, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $be, $ff, $c0, $c1, $ff
db $c0, $c1, $ff, $b6, $b7, $b8, $b9, $ba, $bb, $c0, $c1, $ff, $c0, $c1, $bc, $bd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $ff, $e0, $e1, $ff
db $e0, $e1, $ff, $d6, $d7, $d8, $d9, $da, $db, $e0, $e1, $ff, $e0, $e1, $dc, $dd

db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $dd, $de, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $f6, $f7, $f8, $f9, $fa, $fb, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $c4, $c5, $dd, $de, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $71, $72, $73, $ff, $dc, $dd
db $c4, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c4, $c5, $dd, $de, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $3b, $3c, $3d, $ff, $dc, $dd
db $c4, $c5, $e5, $e5, $e5, $e5, $e5, $e5, $c5, $c5, $dd, $de, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $5b, $5c, $5d, $ff, $dc, $dd
db $c4, $c4, $c4, $c4, $c4, $c4, $c5, $e5, $e5, $c5, $c4, $f0, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $ef, $c5
db $e4, $e4, $e4, $c4, $c5, $c5, $c5, $e4, $e5, $e5, $e4, $e5, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $e4, $e5
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c5
db $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c5, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c5
db $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e5
db $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e5, $e4, $e4, $e5, $e4, $e4, $e4, $c4, $c5
db $c4, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c4, $c5, $c5, $c4, $c5, $c5
db $c5, $c5, $c5, $c5, $c4, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5
db $c4, $c5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e4, $e5, $e5, $e4, $e5, $e5
db $e5, $e5, $e5, $e5, $e4, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5
db $c4, $c5, $c5, $c4, $c5, $c5, $c5, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c5, $c4, $c5
db $e4, $c4, $c4, $c5, $e5, $e5, $e5, $e4, $c4, $c5, $e4, $c4, $c5, $e4, $c4, $c5
db $c4, $c5, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e4, $e4, $c4, $c4, $c5
db $c4, $c4, $c5, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $c4, $c4, $c4, $c5, $c4, $c5, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e4, $e4, $e5, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5
db $e4, $e4, $e4, $e5, $e4, $e5, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $c4, $c5

db $c4, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c4, $c5, $c5, $c4, $c5, $c5
db $c5, $c4, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5
db $c4, $c5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e4, $e5, $e5, $e4, $e5, $e5
db $e5, $e4, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c5, $c5
db $c5, $c5, $c5, $c5, $c4, $c5, $c5, $c4, $c5, $c4, $c5, $c4, $c5, $c5, $c4, $c5
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $c4, $c5, $e5, $e5
db $e5, $e5, $e5, $e5, $e4, $e5, $e5, $e4, $e5, $e4, $e5, $e4, $e5, $e5, $e4, $e5
db $c4, $c4, $c4, $c4, $c4, $c4, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $e4, $e4, $e4, $e4, $c4, $c5
db $e4, $e4, $e4, $e4, $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $f1, $c5, $c4, $c4, $e4, $e5
db $c4, $c5, $c5, $c5, $dd, $de, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $dc, $dd, $c4, $c4, $c4, $c5
db $e4, $e5, $e5, $f2, $fd, $fe, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $fc, $fd, $f1, $e4, $e4, $e5

db $c4, $c5, $dd, $de, $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c2, $c3, $dc, $dd, $c4, $c5
db $e4, $f2, $fd, $fe, $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40, $41, $42
db $43, $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e2, $e3, $fc, $fd, $f1, $e5
db $dd, $de, $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c0, $c1, $60, $61, $62
db $63, $64, $65, $c0, $c1, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c2, $c3, $dc, $dd
db $dd, $de, $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $80, $81, $82
db $83, $84, $85, $e0, $e1, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e2, $e3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff, $a0, $a1, $a2
db $a3, $a4, $a5, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff, $ff, $ff, $bc, $bd, $bd, $bd
db $bd, $bd, $bd, $be, $ff, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $ff, $dc, $dd
db $fd, $fe, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $dd, $dd
db $dd, $dd, $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $fc, $fd
db $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bc, $bd, $ef, $c4, $c4, $c5
db $c4, $c5, $c5, $f0, $bd, $be, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c2, $c3
db $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e4, $c4, $c4
db $e4, $e5, $e5, $e5, $dd, $de, $ff, $ff, $ff, $ff, $74, $75, $76, $ff, $e2, $e3
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bc, $bd, $ef, $c5, $c5, $c5, $e4, $e4
db $e4, $e4, $e4, $e5, $c5, $f0, $bd, $be, $ff, $ff, $3b, $3c, $3d, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e5, $e5, $e5, $e5, $e5
db $e5, $e5, $e5, $e5, $e5, $e5, $dd, $de, $ff, $ff, $5b, $5c, $5d, $ff, $ff, $ff
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $ef, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $c4, $c4, $c4, $c4, $c4, $c5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e4, $e4, $e4, $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fe, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $c4, $c5, $dd, $de, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $e4, $f2, $fd, $fe, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $dd, $de, $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $f2, $fd, $fe, $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40, $41
db $42, $43, $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $c2, $c3, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $60, $61
db $62, $63, $64, $65, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $ff, $dc, $dd
db $dd, $de, $e2, $e3, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $80, $81
db $82, $83, $84, $85, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $a0, $a1
db $a2, $a3, $a4, $a5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $bc, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $ef, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $dc, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $e4, $e5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5

db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $c4, $c5, $c5, $c5
db $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $c5, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e5, $e5, $e5
db $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $e5, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $ff, $dc, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $c4, $c5
db $dd, $de, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $ff, $fc, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $f1, $e5
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $96, $97
db $98, $99, $9a, $9b, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $b6, $b7
db $b8, $b9, $ba, $bb, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $d6, $d7
db $d8, $d9, $da, $db, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $ff, $dc, $dd
db $c4, $f0, $bd, $be, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f6, $f7
db $f8, $f9, $fa, $fb, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $74, $75, $76, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $c4, $f0, $bd, $be, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $3b, $3c, $3d, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $c4, $c5, $e4, $e5, $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $5b, $5c, $5d, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $c4, $c5, $c4, $c5, $c4, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $be, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $e4, $e5, $e4, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $ff, $ff, $ff, $ff, $dc, $dd

db $c4, $c5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $c4, $c5
db $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $f1, $e5
db $dd, $de, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $dc, $dd
db $dd, $de, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40, $41
db $42, $43, $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $60, $61
db $62, $63, $64, $65, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $80, $81
db $82, $83, $84, $85, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $a0, $a1
db $a2, $a3, $a4, $a5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $c4, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $be, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $f2, $fd, $fe, $ff, $ff, $ff, $ff, $dc, $dd
db $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c4, $c5, $dd, $de, $c2, $c3, $ff, $ff, $ff, $ff, $dc, $dd
db $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e4, $f2, $fd, $fe, $e2, $e3, $c0, $c1, $ff, $ff, $dc, $dd

db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $c5, $c4, $c4, $c5, $dd, $de, $c2, $c3, $ff, $ff, $e0, $e1, $ff, $ff, $dc, $dd
db $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5
db $e5, $c5, $c5, $f2, $fd, $fe, $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4
db $c4, $c4, $c5, $de, $c2, $c3, $ff, $c0, $c1, $ff, $ff, $ff, $bc, $bd, $ef, $c5
db $e4, $e4, $c4, $c5, $c5, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $c5, $c5, $e4, $e4
db $e4, $f2, $fd, $fe, $e2, $e3, $ff, $e0, $e1, $ff, $ff, $ff, $dc, $dd, $e4, $e5
db $e4, $c4, $c4, $c5, $e5, $c4, $c5, $c4, $c4, $c5, $e4, $e5, $e5, $e5, $c5, $c5
db $dd, $de, $c2, $c3, $ff, $ff, $ff, $ff, $ff, $ff, $bc, $bd, $ef, $c5, $c4, $c5
db $e4, $e4, $e4, $e5, $e4, $e4, $e5, $c5, $c5, $c4, $c4, $c5, $e4, $e5, $e5, $f2
db $fd, $fe, $e2, $e3, $c0, $c1, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e5, $e4, $e5
db $e4, $e5, $c4, $c4, $c4, $c4, $c5, $e5, $e5, $c5, $c5, $c5, $c4, $c5, $dd, $de
db $c2, $c3, $ff, $ff, $e0, $e1, $ff, $ff, $bc, $bd, $ef, $c4, $c4, $c4, $c4, $c5
db $e4, $e5, $e4, $e4, $e4, $e4, $e5, $e4, $e5, $e5, $e5, $e5, $e4, $f2, $fd, $fe
db $e2, $e3, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e5

db $e4, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $de, $c2, $c3
db $ff, $c0, $c1, $ff, $ff, $ff, $bc, $bd, $ef, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e5, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fe, $e2, $e3
db $ff, $e0, $e1, $ff, $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5
db $dd, $de, $c2, $c3, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $c3, $c2, $c3, $ff, $ff
db $ff, $ff, $ff, $ff, $bc, $bd, $ef, $c4, $c5, $c4, $c4, $c5, $c4, $c4, $c4, $c5
db $dd, $de, $e2, $e3, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $e3, $e2, $e3, $c0, $c1
db $ff, $ff, $ff, $ff, $dc, $dd, $e4, $e4, $e5, $e4, $e4, $e5, $e4, $e4, $e4, $e5
db $dd, $de, $66, $67, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $e0, $e1
db $ff, $ff, $bc, $bd, $ef, $c4, $c4, $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c5
db $dd, $de, $86, $87, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $dc, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e5
db $e5, $f0, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd, $bd
db $bd, $bd, $ef, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e5, $e5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd

db $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
db $c4, $c4, $c4, $c4, $c5, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c5
db $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4
db $e4, $e4, $e4, $e4, $e5, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e4, $e5
db $c4, $c5, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd
db $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $dd, $c4, $c5
db $e4, $f2, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd
db $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $fd, $f1, $e5
db $dd, $de, $c2, $c3, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2
db $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c2, $c3, $dc, $dd
db $dd, $de, $e2, $e3, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2
db $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e2, $e3, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd
db $dd, $de, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $40
db $41, $42, $43, $44, $45, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $dc, $dd

db $dd, $de, $ff, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $60
db $61, $62, $63, $64, $65, $c0, $c1, $ff, $c0, $c1, $ff, $c0, $c1, $ff, $dc, $dd
db $fd, $fe, $ff, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $80
db $81, $82, $83, $84, $85, $e0, $e1, $ff, $e0, $e1, $ff, $e0, $e1, $ff, $fc, $fd
db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $a0
db $a1, $a2, $a3, $a4, $a5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $8e, $8f, $90, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7d, $7e, $7f
db $ff, $7a, $7b, $7c, $ff, $77, $78, $79, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ae, $af, $b0, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ae, $af, $b0
db $ff, $ae, $af, $b0, $ff, $ae, $af, $b0, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $ff, $ff, $ff, $ce, $cf, $d0, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ce, $cf, $d0
db $ff, $ce, $cf, $d0, $ff, $ce, $cf, $d0, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
db $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3
db $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3, $b2, $b3
db $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3
db $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3, $d2, $d3

