INCLUDE "../include/constants.asm"
INCLUDE "../include/ramSymbols.asm"

INCLUDE "hardware.inc"
INCLUDE "bank_000.asm"
INCLUDE "bank_001.asm"
INCLUDE "bank_002.asm"
INCLUDE "bank_003.asm"
INCLUDE "bank_004.asm"
INCLUDE "bank_005.asm"
INCLUDE "../src/stages.asm"
INCLUDE "../src/pad.asm"
INCLUDE "../src/images.asm"
INCLUDE "../src/music.asm"
INCLUDE "../src/end.asm"