INCLUDE "include/constants.asm"
INCLUDE "include/ramSymbols.asm"

INCLUDE "include/hardware.asm"
INCLUDE "src/bank_000.asm"
INCLUDE "src/bank_001.asm"
INCLUDE "src/bank_002.asm"
INCLUDE "src/bank_003.asm"
INCLUDE "src/bank_004.asm"
INCLUDE "src/bank_005.asm"
INCLUDE "src/stages.asm"
INCLUDE "src/pad.asm"
INCLUDE "src/images.asm"
INCLUDE "src/music.asm"
INCLUDE "src/end.asm"