demos_1:
    demo_input PADF_NONE, 18
    demo_input PADF_RIGHT, 32
    demo_input PADF_NONE, 37
    demo_input PADF_LEFT, 41
    demo_input PADF_NONE, 51
    demo_input PADF_RIGHT, 38
    demo_input PADF_NONE, 37
    demo_input PADF_A, 10
    demo_input PADF_NONE, 5
    demo_input PADF_RIGHT, 23
    demo_input PADF_NONE, 110
    demo_input PADF_LEFT, 39
    demo_input PADF_NONE, 26
    demo_input PADF_LEFT, 5
    demo_input PADF_NONE, 18
    demo_input PADF_LEFT, 7
    demo_input PADF_NONE, 10
    demo_input PADF_LEFT, 5
    demo_input PADF_NONE, 13
    demo_input PADF_LEFT, 5
    demo_input PADF_NONE, 75
    demo_input PADF_RIGHT, 5
    demo_input PADF_NONE, 18
    demo_input PADF_RIGHT, 34
    demo_input PADF_NONE, 13
    demo_input PADF_LEFT, 11
    demo_input PADF_NONE, 32
    demo_input PADF_RIGHT, 13
    demo_input PADF_NONE, 9
    demo_input PADF_LEFT, 11
    demo_input PADF_NONE, 17
    demo_input PADF_RIGHT, 6
    demo_input PADF_NONE, 12
    demo_input PADF_LEFT, 7
    demo_input PADF_NONE, 33
    demo_input PADF_LEFT, 33
    demo_input PADF_NONE, 28
    demo_input PADF_LEFT, 9
    demo_input PADF_NONE, 24
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 19
    demo_input PADF_RIGHT, 8
    demo_input PADF_NONE, 13
    demo_input PADF_A, 10
    demo_input PADF_NONE, 15
    demo_input PADF_RIGHT, 3
    demo_input PADF_NONE, 42
    demo_input PADF_RIGHT, 4
    demo_input PADF_NONE, 53
    demo_input PADF_A, 13
    demo_input PADF_NONE, 16
    demo_input PADF_RIGHT, 40
    demo_input PADF_NONE, 45
    demo_input PADF_A, 10
    demo_input PADF_NONE, 2
    demo_input PADF_RIGHT, 31
    demo_input PADF_NONE, 57
    demo_input PADF_RIGHT, 97
    demo_input PADF_NONE, 27
    demo_input PADF_LEFT, 8
    demo_input PADF_NONE, 23
    demo_input PADF_RIGHT, 40
    demo_input PADF_NONE, 25
    demo_input PADF_LEFT, 15
    demo_input PADF_A | PADF_LEFT, 12
    demo_input PADF_LEFT, 41
    demo_input PADF_NONE, 23
    demo_input PADF_RIGHT, 18
    demo_input PADF_NONE, 20
    demo_input PADF_LEFT, 33
    demo_input PADF_NONE, 17
    demo_input PADF_RIGHT, 25
    demo_input PADF_NONE, 19
    demo_input PADF_RIGHT, 15
    demo_input PADF_NONE, 26
    demo_input PADF_RIGHT, 20
    demo_input PADF_NONE, 16
    demo_input PADF_RIGHT, 10
    demo_input PADF_NONE, 18
    demo_input PADF_LEFT, 22
    demo_input PADF_NONE, 12
    demo_input PADF_RIGHT, 29
    demo_input PADF_NONE, 18
    demo_input PADF_LEFT, 29
    demo_input PADF_NONE, 26
    demo_input PADF_RIGHT, 23
    demo_input PADF_NONE, 22
    demo_input PADF_LEFT, 60
    demo_input PADF_NONE, 15
    demo_input PADF_RIGHT, 4
    demo_input PADF_NONE, 33
    demo_input PADF_RIGHT, 4
    demo_input PADF_NONE, 51
    demo_input PADF_RIGHT, 24
    demo_input PADF_NONE, 57
    demo_input PADF_RIGHT, 3
    demo_input PADF_NONE, 8
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 62
    demo_input PADF_LEFT, 25
    demo_input PADF_NONE, 38
    demo_input PADF_LEFT, 30
    demo_input PADF_NONE, 41
    demo_input PADF_LEFT, 21
    demo_input PADF_NONE, 14
    demo_input PADF_RIGHT, 7
    demo_input PADF_NONE, 38
    demo_input PADF_RIGHT, 8
    demo_input PADF_NONE, 10
    demo_input PADF_RIGHT, 30
    demo_input PADF_NONE, 25
    demo_input PADF_RIGHT, 8
    demo_input PADF_NONE, 64
    demo_input PADF_RIGHT, 11
    demo_input PADF_NONE, 47
    demo_input PADF_LEFT, 35
    demo_input PADF_NONE, 14
    demo_input PADF_RIGHT, 18
    demo_input PADF_NONE, 21
    demo_input PADF_LEFT, 20
    demo_input PADF_NONE, 108
    demo_input PADF_LEFT, 13
    demo_input PADF_NONE, 19
    demo_input PADF_LEFT, 7
    demo_input PADF_NONE, 44
    demo_input PADF_RIGHT, 13
    demo_input PADF_NONE, 28
    demo_input PADF_LEFT, 27
    demo_input PADF_NONE, 33
    demo_input PADF_RIGHT, 20
    demo_input PADF_NONE, 4
    demo_input PADF_A, 10
    demo_input PADF_NONE, 12
    demo_input PADF_RIGHT, 24
    demo_input PADF_NONE, 14
    demo_input PADF_LEFT, 16
    demo_input PADF_NONE, 7
    demo_input PADF_A, 14
    demo_input PADF_NONE, 10
    demo_input PADF_LEFT, 22
    demo_input PADF_NONE, 33
    demo_input PADF_RIGHT, 29
    demo_input PADF_NONE, 33
    demo_input PADF_RIGHT, 21
    demo_input PADF_NONE, 34
    demo_input PADF_RIGHT, 19
    demo_input PADF_NONE, 26
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 10
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 16
    demo_input PADF_RIGHT, 16
    demo_input PADF_NONE, 1
    demo_input PADF_RIGHT, 5
    demo_input PADF_NONE, 37
    demo_input PADF_LEFT, 136
    demo_input PADF_NONE, 8
    demo_input PADF_RIGHT, 96
    demo_input PADF_NONE, 57
    demo_input PADF_RIGHT, 11
    demo_input PADF_NONE, 20
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 3
    demo_input PADF_RIGHT, 9
    demo_input PADF_NONE, 54
    demo_input PADF_LEFT, 14
    demo_input PADF_NONE, 118
    demo_input PADF_NONE, 0
